name: CI setup for Go

on:
  push: 
    branches: [main]
  pull_request:
    branches: [main]
    
jobs: 
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
    - name: Print a greeting
      run: |
        ls
        echo Hello Lanzs!
        
        
    - name: Setup Go environment  
      uses: actions/setup-go@v2.1.3
      with:
        # The Go version to download (if necessary) and use. Supports semver spec and ranges.
        go-version: 1.13.7
        
    - name: Check Go Version  
      run:  |
        ls
        go version
        
    - name: CheckOut Go Lanzs Codes
      uses: actions/checkout@v2
      
    - name: Check DIR
      run: |
        ls
        cat calc.go
        
    - name: CheckOut Private Repo
      uses: actions/checkout@v2
      with:
        repository: lowkh2/GoSchoolRemoteExample
        path: RemoteRepo
        token: ${{ secrets.BEN_GOREMOTE }}
        
    - name: Check Repo DIR files
      run: |
        ls
        cd RemoteRepo
        ls
        cat myText.txt
        cd ..
       
    - name: Installing Dependencies
      run: |
        go get github.com/franela/goblin
        go get github.com/tebeka/go2xunit
        go test -v | go2xunit > report.xml
        go test -v
        ls
    
    - name: Publish Unit Test Results EnricoMi
      uses: EnricoMi/publish-unit-test-result-action@v1
      if: always()
      with:
        files: report.xml 
    - if: ${{ failure()}}
      name: Create Issues
      uses: nashmaniac/create-issue-action@v1.1
      with:
        title: Build Failed
        token: ${{secrets.GITHUB_TOKEN}}
        assignees: ${{github.actor}}
        labels: workflow-failed
        body: Workflow failed for commit ${{github.sha}}

    - if: ${{ success() }}
      name: Create download directory
      run: mkdir downloads
      
    - name: Prepare Documents
      run: |
        mv report.xml ./downloads
        
    - if: ${{ success() }}
      name: Prepare artifacts
      uses: actions/upload-artifact@v2
      with:
        name: assetDocuments
        path: downloads
    - if: ${{ success() }}
      name: Download Content
      uses: actions/download-artifact@v2
      with:
        name: assetDocuments






        
      
      
      
