name: CI setup for Go

on:
  push: 
    branches: [main]
    
jobs: 
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
    - name: Print a greeting
      run:
        ls
        echo Hello Lanzs!
        
