name: CI setup for Go

on:
  push: 
    branches: [main]
    
jobs: 
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
    - name: Print a greeting
      run: |
        ls
        echo Hello Lanzs!
        
        
    - name: Setup Go environment  
      uses: actions/setup-go@v2.1.3
      with:
        # The Go version to download (if necessary) and use. Supports semver spec and ranges.
        go-version: 1.13.7
        
    - name: Check Go Version  
      run:  |
        ls
        go version
        
    - name: CheckOut Go Lanzs Codes
      uses: actions/checkout@v2
      
    - name: Check DIR
      run: |
        ls
        cat calc.go
        
    - name: CheckOut Private Repo
      uses: actions/checkout@v2
      with:
        repository: lowkh2/GoSchoolRemoteExample
        path: RemoteRepo
        token: ${{ secrets.BEN_GOREMOTE }}
        
    - name: Check Repo DIR files
      run: |
        ls
        cd RemoteRepo
        ls
        cat myText.txt
        cd ..
       
    - name: Installing Dependencies
      run: |
        go get github.com/franela/goblin
        go test -v
    
        
        
      
      
      
